# Generated by Django 3.1.1 on 2020-09-08 05:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.TextField(null=True)),
                ('phone', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vat_regno', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nic', models.CharField(max_length=15, unique=True)),
                ('epfNo', models.IntegerField(null=True, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=50)),
                ('dob', models.DateField()),
                ('maritalStatus', models.CharField(choices=[('Marr', 'Married'), ('UnMarr', 'Unmarried')], max_length=50)),
                ('contactNo', models.CharField(max_length=10, null=True)),
                ('doa', models.DateField(null=True)),
                ('basicSalary', models.FloatField(null=True)),
                ('empType', models.CharField(choices=[('Pay', 'Permanent'), ('Temp', 'Temparory')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Oil_Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.FloatField()),
                ('Date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VehicleNo', models.CharField(max_length=20)),
                ('Status', models.BooleanField()),
                ('NIC', models.CharField(max_length=20)),
                ('EPF_No', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Ambrosia_Project.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bill_No', models.CharField(max_length=10)),
                ('Description', models.TextField()),
                ('Service_Date', models.DateField()),
                ('Next_Service_Date', models.DateField()),
                ('VehicleNo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Ambrosia_Project.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Oil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Container_No', models.IntegerField()),
                ('Consumed_Amount', models.FloatField(null=True)),
                ('Price', models.FloatField(null=True)),
                ('Oil_Stock', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Ambrosia_Project.oil_stock')),
                ('VehicleNo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Ambrosia_Project.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='NormalEmployee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epfNo', models.IntegerField(null=True)),
                ('empGroup', models.CharField(choices=[('staf', 'Staff'), ('facwork', 'FactoryWorker')], max_length=50)),
                ('designation', models.CharField(choices=[('FO', 'Factory_Officer'), ('AFO', 'AssistantFactory_Officer'), ('CLR', 'Clerk'), ('TRA', 'Trainee')], max_length=50)),
                ('nic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Ambrosia_Project.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Driving_Records',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(default=datetime.datetime.now)),
                ('Start_Reading', models.FloatField()),
                ('End_Reading', models.FloatField()),
                ('VehicleNo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Ambrosia_Project.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Driver_License_No', models.CharField(max_length=10)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Ambrosia_Project.employee')),
            ],
        ),
        migrations.CreateModel(
            name='attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('daytype', models.CharField(choices=[('FD', 'FullDay'), ('HD', 'HalfDay')], max_length=20)),
                ('attendaceStatus', models.CharField(choices=[('Pres', 'Present'), ('Abs', 'Absent')], max_length=50)),
                ('workingDays', models.IntegerField()),
                ('nic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Ambrosia_Project.employee')),
            ],
        ),
    ]
