# Generated by Django 3.1.1 on 2020-10-11 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ambrosia_Project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='empImage',
        ),
    ]
