# Generated by Django 3.1.1 on 2020-09-07 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ambrosia_Project', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Buyer',
        ),
        migrations.AlterModelTable(
            name='broker',
            table='Broker',
        ),
    ]
