# Generated by Django 3.1 on 2020-10-08 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ambrosia_Project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeesalary',
            name='advance',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='employeesalary',
            name='allowance_b_price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='employeesalary',
            name='incentive_1',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='employeesalary',
            name='incentive_2',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='employeesalary',
            name='loan',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='employeesalary',
            name='ot_amount_for_month',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='employeesalary',
            name='ot_hours',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='employeesalary',
            name='remaining_salary',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='employeesalary',
            name='tea_advance',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='employeesalary',
            name='total_deduction',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='employeesalary',
            name='total_salary',
            field=models.FloatField(null=True),
        ),
    ]
