# Generated by Django 3.1.1 on 2020-10-09 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ambrosia_Project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_soldstocks',
            name='active',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
