# Generated by Django 3.1.1 on 2020-09-07 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ambrosia_Project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='teaCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'teaCategory',
            },
        ),
    ]
