# Generated by Django 3.1.1 on 2020-09-08 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ambrosia_Project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction_Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice', models.IntegerField(null=True)),
                ('net_weight', models.FloatField()),
                ('total_weight', models.FloatField()),
                ('no_of_packets', models.IntegerField()),
                ('status', models.CharField(choices=[('S', 'Sold'), ('N', 'NotSold'), ('P', 'Pending')], max_length=10)),
                ('sold_count', models.IntegerField()),
                ('price', models.FloatField()),
            ],
            options={
                'db_table': 'Auction_Stock',
            },
        ),
        migrations.AlterModelTable(
            name='buyer',
            table='Buyer',
        ),
    ]
