# Generated by Django 3.1 on 2020-09-07 11:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ambrosia_Project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('emp_etf', models.FloatField()),
                ('epf_employee', models.FloatField()),
                ('epf_employer', models.FloatField()),
            ],
            options={
                'db_table': 'funds',
            },
        ),
    ]
