# Generated by Django 3.1.1 on 2020-09-07 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ambrosia_Project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sup_Name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=100, null=True)),
                ('DOB', models.DateField()),
                ('Reg_Date', models.DateField()),
                ('phone', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LeafStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('rec_Date', models.DateField()),
                ('rec_Time', models.TimeField()),
                ('supplier_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ambrosia_Project.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Estate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('route', models.CharField(choices=[('WE', 'Tes1'), ('BR', 'Test2'), ('BNR', 'Testt3')], max_length=3)),
                ('sup_scale', models.CharField(choices=[('sm', 'Small-Scale'), ('lg', 'Large-Scale')], max_length=2)),
                ('supplier_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ambrosia_Project.supplier')),
            ],
        ),
    ]
