# Generated by Django 3.1.1 on 2020-09-07 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ambrosia_Project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeafInventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_Date', models.DateField()),
                ('in_Time', models.TimeField()),
                ('tray_Id', models.IntegerField()),
                ('temp', models.FloatField()),
                ('weight', models.FloatField()),
                ('out_Date', models.DateField()),
                ('out_Time', models.TimeField()),
            ],
            options={
                'db_table': 'inventory',
            },
        ),
    ]
