# Generated by Django 3.1.1 on 2020-09-07 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ambrosia_Project', '0002_teacategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='categoryProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cp_id', models.CharField(max_length=10)),
                ('price', models.FloatField()),
                ('category_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Ambrosia_Project.teacategory')),
                ('packet_weight_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Ambrosia_Project.packettype')),
            ],
        ),
    ]
