# Generated by Django 3.1.1 on 2020-09-07 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ambrosia_Project', '0002_estate_leafstock_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estate',
            name='supplier_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Ambrosia_Project.supplier'),
        ),
        migrations.AlterField(
            model_name='leafstock',
            name='supplier_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Ambrosia_Project.supplier'),
        ),
    ]
