# Generated by Django 3.1 on 2020-09-07 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ambrosia_Project', '0002_funds'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='funds',
            table='funds',
        ),
    ]
