# Generated by Django 3.1 on 2020-09-08 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ambrosia_Project', '0002_auto_20200908_1304'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='buyer',
            table=None,
        ),
        migrations.AlterModelTable(
            name='driver',
            table='Buyer',
        ),
    ]
