# Generated by Django 3.1.1 on 2020-09-07 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ambrosia_Project', '0003_teagrades'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tea_add_prod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_weight', models.FloatField()),
                ('bopf_w', models.FloatField()),
                ('dust_1_w', models.FloatField()),
                ('dust_2_w', models.FloatField()),
                ('dust_3_w', models.FloatField()),
            ],
            options={
                'db_table': 'add_product',
            },
        ),
    ]
