# Generated by Django 3.1.1 on 2020-09-07 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ambrosia_Project', '0004_preorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Packet_stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_ID', models.CharField(max_length=10)),
                ('no_ofPackets', models.IntegerField()),
                ('date', models.DateField()),
                ('cp_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Ambrosia_Project.categoryproduct')),
            ],
        ),
        migrations.CreateModel(
            name='Accumulate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noOf_Packets', models.IntegerField()),
                ('cp_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Ambrosia_Project.categoryproduct')),
            ],
        ),
    ]
