# Generated by Django 3.1.1 on 2020-09-08 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ambrosia_Project', '0004_tea_add_prod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tea_add_prod',
            name='bopf_w',
        ),
        migrations.RemoveField(
            model_name='tea_add_prod',
            name='dust_1_w',
        ),
        migrations.RemoveField(
            model_name='tea_add_prod',
            name='dust_2_w',
        ),
        migrations.RemoveField(
            model_name='tea_add_prod',
            name='dust_3_w',
        ),
        migrations.AddField(
            model_name='tea_add_prod',
            name='tea_grades',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Ambrosia_Project.teagrades'),
        ),
    ]
